language: ruby
rvm:
  - 1.9.3
env:
  - DB=test
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
bundler_args: --binstubs=./bundler_stubs
services:
  - elasticsearch
