defaults: &defaults
  pool: 5
  timeout: 5000
  database: jortal_<%= Rails.env %>
  adapter: postgresql

postgresql: &postgresql
  <<: *defaults
  username: postgres
  password:
  host: localhost

development:
  <<: *defaults
  username: saasbook
  password:
 
test: &test
  <<: *defaults
  username: saasbook
  password:
 
production:
  <<: *defaults
  username: postgres
  password:

cucumber:
  <<: *test
