defaults: &defaults
  pool: 5
  timeout: 5000
  database: jortal_<%= Rails.env %>
  adapter: postgresql
  username: postgres
  password:

postgresql: &postgresql
  <<: *defaults
  host: localhost

development:
  <<: *defaults
 
test: &test
  <<: *defaults
 
production:
  <<: *defaults

cucumber:
  <<: *test

