defaults: &defaults
  pool: 5
  timeout: 5000

postgresql: &postgresql
  <<: *defaults
  host: localhost
  database: jortal_<%= Rails.env %>
  adapter: postgresql
  username: postgres
  password:

sqlite3: &sqlite3
  <<: *defaults
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

development:
  <<: *sqlite3
 
test: &test
  <<: *sqlite3
 
production:
  <<: *defaults

cucumber:
  <<: *test

